import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'surface-container-highest': '#d5e3fc',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e6eeff',
        'tertiary-fixed-dim': '#ffb59d',
        'primary-fixed-dim': '#b3c5ff',
        'on-error': '#ffffff',
        'surface-variant': '#d5e3fc',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-container': '#f8f7ff',
        'tertiary-fixed': '#ffdbd0',
        'on-tertiary-fixed': '#390c00',
        'on-primary-fixed-variant': '#003fa4',
        'secondary': '#425ca0',
        'background': '#f8f9ff',
        'inverse-primary': '#b3c5ff',
        'surface': '#f8f9ff',
        'primary': '#0050cb',
        'secondary-container': '#9bb4fe',
        'inverse-on-surface': '#eaf1ff',
        'tertiary': '#a33200',
        'primary-container': '#0066ff',
        'on-surface': '#0d1c2e',
        'secondary-fixed-dim': '#b3c5ff',
        'secondary-fixed': '#dae1ff',
        'on-secondary-fixed-variant': '#284386',
        'outline-variant': '#c2c6d8',
        'on-primary': '#ffffff',
        'inverse-surface': '#233144',
        'primary-fixed': '#dae1ff',
        'surface-container-low': '#eff4ff',
        'surface-bright': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'surface-tint': '#0054d6',
        'surface-dim': '#ccdbf3',
        'on-surface-variant': '#424656',
        'error': '#ba1a1a',
        'on-secondary-container': '#294487',
        'on-primary-fixed': '#001849',
        'tertiary-container': '#cc4204',
        'on-tertiary-container': '#fff6f4',
        'on-tertiary-fixed-variant': '#832600',
        'outline': '#727687',
        'on-secondary-fixed': '#001849',
        'on-background': '#0d1c2e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'blue-sm': '0 4px 20px rgba(0, 80, 203, 0.08)',
        'blue-md': '0 20px 40px rgba(0, 80, 203, 0.06)',
        'blue-lg': '0 40px 60px rgba(0, 80, 203, 0.08)',
        'blue-xl': '0 40px 80px rgba(0, 80, 203, 0.1)',
      },
    },
  },
  plugins: [],
}

export default config
